version: "2"
services:
    www:
        build: .
        container_name: php-apache
        ports:
            - "8001:80"
        volumes:
            - ./src/:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: passlocalhost123
            MYSQL_ROOT_PASSWORD: passlocalhost123
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: passlocalhost123
            MYSQL_ROOT_PASSWORD: passlocalhost123

volumes:
    persistent:
